[package]
name = "orbit-bin"
version = "0.1.0"
edition = "2024"

[dependencies]
orbit-kernel = { path = "../orbit-kernel" }
orbit-app = { path = "../orbit-app" }

[features]
default = [ "ch32v208wbu6" ]
ch592 = [ "orbit-kernel/ch592", "orbit-app/ch592" ]
ch32v208wbu6 = [ "orbit-kernel/ch32v208wbu6", "orbit-app/ch32v208wbu6" ]
