[workspace]
members = [
    "calc",
    "eink_lib",
    "font_8x10",
    "math",
    "my_app",
    "my_lib",
    "my_lib2",
    "orbit-app-common", "orbit-app-new-proc-macro",
    "orbit-app-proc-macro",
    "reade",
    "reade_3",
    "spi_app",
]
exclude = [
    "test_app",
    "reade_4_2",
    "eink_lib_4_2",
]
resolver = "2"
