[package]
name = "orbit"
version = "0.1.0"
authors = ["wooker <zakhar.semyonov@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
esp-hal = { version = "0.16.0", features = [ "esp32c3" ], optional = true}

[workspace]
members = [
    "chips/esp32-c3"
]

[features]
esp32-c3 = ["dep:esp-hal"]
