[package]
name = "orbit"
version = "0.1.0"
authors = ["wooker <zakhar.semyonov@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = { version = "0.4.20" }
esp-hal = { version = "0.16.0", features = [ "esp32c3"] }
esp-alloc = { version="0.3.0" }
esp-println = { version = "0.9.0", features = [ "log", "esp32c3" ] }
esp-backtrace = { version = "0.11.0", features = [
    "exception-handler",
    "panic-handler",
    "println",
    "esp32c3"
] }

# esp
embedded-svc = { version = "0.26.1", default-features = false, features = [], optional = true}
embedded-io = { version="0.6.1", optional = true}
esp-wifi = { version = "0.4.0", features = [
    "phy-enable-usb",
    "utils",
    "wifi-default",
    "esp-now",
], optional = true}

[workspace]
exclude = [
    "chips/esp32-c3"
]

[features]
esp32c3 = [
    "esp-hal/esp32c3",
    "esp-wifi/esp32c3"
]
