[package]
name = "orbit-kernel"
version = "0.1.0"
edition = "2021"
description = "Orbit kernel crate"

[dependencies]
orbit-arch = { path = "../orbit-arch"}
chips = { path = "../chips" }

[features]
ch32v208wbu6 = [ "orbit-arch/qingke_v4", "chips/ch32v208wbu6" ]
ch592 = [ "orbit-arch/qingke_v4", "chips/ch592" ]
esp32c3 = [ "orbit-arch/esp_riscv", "chips/esp32c3" ]
