[package]
name = "orbit-kernel"
version = "0.1.0"
edition = "2021"
description = "Orbit kernel crate"

[dependencies]
orbit-arch = { path = "../orbit-arch"}
ch32-metapac = { git = "https://github.com/ch32-rs/ch32-metapac.git", rev = "ch32-data-ea7624e62a0c2faf0a239db14e676f3767a0601b" }

[features]
default = ["ch32v208"]
ch32v208 = ["orbit-arch/qingke_v4", "ch32-metapac/ch32v208wbu6","ch32-metapac/rt","ch32-metapac/memory-x"]
