[package]
name = "orbit-kernel"
version = "0.1.0"
edition = "2021"
description = "Orbit kernel crate"

[dependencies]
fugit = "0.3.7"
embedded-hal = "1.0.0"
orbit-arch = { path = "../orbit-arch"}
orbit-common = { path = "../orbit-common" }
orbit-common-proc-macro = { path = "../orbit-common-proc-macro" }
chip = { path = "../chip" }

[features]
pfic = []
ch32v208wbu6 = [ "orbit-arch/qingke_v4", "chip/ch32v208wbu6" ]
ch32x035 = [ "orbit-arch/qingke_v4", "chip/ch32x035" ]
ch592 = [ "orbit-arch/qingke_v4", "chip/ch592" ]
esp32c3 = [ "orbit-arch/esp_riscv", "chip/esp32c3" ]
ch32v003 = [ "orbit-arch/qingke_v2", "chip/ch32v003" ]
bl702 = [ "orbit-arch/riscv", "chip/bl702" ]
