[target.riscv32imc-unknown-none-elf]
runner = "espflash flash --monitor"

[env]
ESP_LOGLEVEL="INFO"

[alias]
kernel = "build -p orbit-kernel --features"
kernel-size = "size -p orbit-kernel --features"
kernel-objdump = "objdump -p orbit-kernel --features"
bin = "build -p orbit-bin --features"
bin-size = "size -p orbit-bin --features"
bin-objdump = "objdump -p orbit-bin --features"

app = "build -p orbit-app --bin"

# Same as release
[profile.dev]
# opt-level = 1
# debug = true
# # split-debuginfo = '...'  # Platform-specific.
# # strip = "none"
# debug-assertions = true
# overflow-checks = false
# lto = false
# panic = 'unwind'
# incremental = false
# codegen-units = 16
# rpath = false

[build]
target = "riscv32imc-unknown-none-elf"

[unstable]
build-std = ["alloc", "core"]
