[target.riscv32imc-unknown-none-elf]
runner = "espflash flash --monitor"

[env]
ESP_LOGLEVEL="INFO"

[alias]
kernel-size = "size --bin orbit-kernel"
kernel-section-size = "size --bin orbit-kernel -- -A -x"
kernel-objdump = "objdump --bin orbit-kernel -- -d --demangle"

# [build]
# rustflags = [
#   # "-C", "link-arg=-Tlinkall.x",

#   # "-C", "link-arg=-Trom_functions.x",

#   # Required to obtain backtraces (e.g. when using the "esp-backtrace" crate.)
#   # NOTE: May negatively impact performance of produced code
#   # "-C", "force-frame-pointers",
# ]

[unstable]
build-std = ["alloc", "core"]
