[target.riscv32imc-unknown-none-elf]
runner = "espflash flash --monitor"

[env]
ESP_LOGLEVEL="INFO"

[alias]
kernel = "build -p orbit-kernel --features"
kernel-size = "size -p orbit-kernel --features"
kernel-objdump = "objdump -p orbit-kernel --features"

[build]
target = "riscv32imc-unknown-none-elf"

[unstable]
build-std = ["alloc", "core"]
