[package]
name = "chips"
version = "0.1.0"
edition = "2024"
description = "Library crate containing linker scripts for a given microcontroller"

[dependencies]
ch32v2 = { version = "0.1.6", optional = true }
ch59x = { version = "0.1.8", optional = true }

[features]
esp32c3 = []
ch32v208wbu6 = [ "ch32v2/ch32v20x", "ch32v2/critical-section" ]
ch592 = ["ch59x/ch59x", "ch59x/critical-section"]
