[package]
name = "orbit-app"
version = "0.1.0"
edition = "2021"
description = "Crate contaning application binaries"
links = "orbit-app" # to allow passing env vars to dependent crates

[dependencies]
orbit-common = { path = "../orbit-common" }
orbit-common-proc-macro = { path = "../orbit-common-proc-macro" }

# Can use either kernel, custom LibOS, or external library
orbit-kernel = { path = "../orbit-kernel" }
orbit-libos = { path = "../orbit-libos" }

[features]
ch592 = [ "orbit-kernel/ch592", "orbit-libos/ch592" ]
ch32v208wbu6 = [ "orbit-kernel/ch32v208wbu6", "orbit-libos/ch32v208wbu6" ]
ch32x035 = [ "orbit-kernel/ch32x035", "orbit-libos/ch32x035" ]
ch32v003 = [ "orbit-kernel/ch32v003", "orbit-libos/ch32v003" ]
bl702 = [ "orbit-kernel/bl702", "orbit-libos/bl702" ]
