[package]
name = "orbit-app"
version = "0.1.0"
edition = "2021"
description = "Crate contaning application binaries"
links = "orbit-app" # to allow passing env vars to dependent crates

[dependencies]
orbit-common = { path = "../orbit-common" }
orbit-common-proc-macro = { path = "../orbit-common-proc-macro" }

# Can use either kernel, custom LibOS, or external library
orbit-kernel = { path = "../orbit-kernel" }
orbit-libos = { path = "../orbit-libos" }

postcard = { version = "1.1.1", default-features = false }
serde = { version="1.0.*", default-features = false }

# [profile.dev]
# opt-level=0

[features]
default = [ "app-wfi" ]
ch592 = [ "orbit-kernel/ch592", "orbit-libos/ch592" ]
ch32v208wbu6 = [ "orbit-kernel/ch32v208wbu6", "orbit-libos/ch32v208wbu6", "app-blinky" ]
ch32v003 = [ "orbit-kernel/ch32v003", "orbit-libos/ch32v003", "app-uart", "app-blinky" ]
bl702 = [ "orbit-kernel/bl702", "orbit-libos/bl702" ]

app-wfi = []
app-uart = []
app-blinky = []

[[bin]]
name = "test"
