[package]
name = "orbit-app"
version = "0.1.0"
edition = "2021"
description = "Crate contaning application binaries"

[dependencies]
orbit-common = { path = "../orbit-common" }
# Can use either kernel, custom LibOS, or external HAL
orbit-kernel = { path = "../orbit-kernel" }
orbit-libos = { path = "../orbit-libos" }
# ch32-hal = { git = "https://github.com/ch32-rs/ch32-hal.git", rev = "3ccf0c87ed952b2d8bef7b9e6193e5059a00101c", default-features = false, features = ["ch32v208wbu6", "memory-x", "rt"] }

# [profile.dev]
# opt-level=0

[features]
ch592 = [ "orbit-kernel/ch592", "orbit-libos/ch592" ]
ch32v208wbu6 = [ "orbit-kernel/ch32v208wbu6", "orbit-libos/ch32v208wbu6" ]
