[package]
name = "eink_lib"
version = "0.1.0"
edition = "2024"
links = "libos_eink_lib" # Needed for linking in orbit-bin
build = ".cargo/build.rs"

[dependencies]
orbit-app-common = { path = "../orbit-app-common" }
orbit-app-proc-macro = { path = "../orbit-app-proc-macro" }
orbit-common = { path =  "../../orbit-common" }

orbit-kernel = { path = "../../orbit-kernel" , features = [ "ch32x035" ]}

ch32x035_spi_driver = { path = "../ch32x035_spi_driver" }
